### PR TITLE
2016 updates

### PR DESCRIPTION
**Pull request by erik-helleren**
Added the video back to the home page, edited the copy on the home page, and updated Dates and Rates for 2016.

### CODE REVIEW

**Comment by erik-helleren** [comment]
Avand, what is the format of the URL for the automatic deployments for heroku?

**Comment by erik-helleren** [comment]
Please don't deploy. As I said in the comments, it's not ready yet.

**Comment by avand** [comment]
The format is: wlcamp-pr-XXX.herokuapp.com, where XXX is the ID of the pull request. I missed your comment, sorry. Went ahead and rolled back the deploy.

**Comment by erik-helleren** [comment]
Thank You.

**Pull request merged**
