### PR TITLE
Jan promo

### PR DESCRIPTION
**Pull request by erik-helleren**
This PR is still in the review phase, please _don't merge_ until the office gives the ok.

### CODE REVIEW

**Comment by erik-helleren** [comment]
Got approval to launch.  What is the new way that we are launching to prod?  Does just merging to master do it now that we have the heroku git hooks?

**Comment by avand** [comment]
Yep! Just merge and you're done.

**Comment by erik-helleren** [comment]
So, I think there was a hickup with the heroku integration... I merged to master, but no new deployment yet.

**Comment by avand** [comment]
Sorry about that @erik-helleren, it looks like Heroku wasn't supporting our stack anymore (cedar-10) anymore. But the upgrade path is easy so I just upgraded the stack and manually deployed. The automatic deploys should continue to work now.

p.s. could you add an profile picture to your GitHub account?

**Pull request merged**
